function(set_cpp14 NAME)
  if (${CMAKE_VERSION} VERSION_GREATER "3.2")
    set_property(TARGET ${NAME} PROPERTY CXX_STANDARD 14)
    set_property(TARGET ${NAME} PROPERTY CXX_STANDARD_REQUIRED ON)
  else (${CMAKE_VERSION} VERSION_GREATER "3.2")
    set_target_properties(${NAME} PROPERTIES COMPILE_FLAGS "-std=c++1y")
  endif (${CMAKE_VERSION} VERSION_GREATER "3.2")
endfunction(set_cpp14)
